//go:build go1.16
// +build go1.16

// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package main

import (
	"context"
	"errors"
	"fmt"
	"net/http"
	"net/url"
	"strconv"
	"strings"

	"github.com/Azure/azure-sdk-for-go/sdk/azcore/policy"
	"github.com/Azure/azure-sdk-for-go/sdk/azcore/runtime"
)

type entityClient struct {
	con *connection
}

// Delete - Delete the Queue or Topic with the given entityName.
// If the operation fails it returns the *ServiceBusManagementError error type.
func (client *entityClient) Delete(ctx context.Context, entityName string, options *EntityDeleteOptions) (EntityDeleteResponse, error) {
	req, err := client.deleteCreateRequest(ctx, entityName, options)
	if err != nil {
		return EntityDeleteResponse{}, err
	}
	resp, err := 	client.con.Pipeline().Do(req)
	if err != nil {
		return EntityDeleteResponse{}, err
	}
	if !runtime.HasStatusCode(resp, http.StatusOK) {
		return EntityDeleteResponse{}, client.deleteHandleError(resp)
	}
	return client.deleteHandleResponse(resp)
}

// deleteCreateRequest creates the Delete request.
func (client *entityClient) deleteCreateRequest(ctx context.Context, entityName string, options *EntityDeleteOptions) (*policy.Request, error) {
	urlPath := "/{entityName}"
	if entityName == "" {
		return nil, errors.New("parameter entityName cannot be empty")
	}
	urlPath = strings.ReplaceAll(urlPath, "{entityName}", url.PathEscape(entityName))
	req, err := runtime.NewRequest(ctx, http.MethodDelete, runtime.JoinPaths(client.con.Endpoint(), urlPath))
	if err != nil {
		return nil, err
	}
	reqQP := req.Raw().URL.Query()
	if client.apiVersion != nil {
		reqQP.Set("api-version", "2017_04")
	}
	req.Raw().URL.RawQuery = reqQP.Encode()
	req.Raw().Header.Set("Accept", "application/xml, application/atom+xml")
	return req, nil
}

// deleteHandleResponse handles the Delete response.
func (client *entityClient) deleteHandleResponse(resp *http.Response) (EntityDeleteResponse, error) {
	result := EntityDeleteResponse{RawResponse: resp}
	if err := runtime.UnmarshalAsXML(resp, &result.Object); err != nil {
		return EntityDeleteResponse{}, err
	}
	return result, nil
}

// deleteHandleError handles the Delete error response.
func (client *entityClient) deleteHandleError(resp *http.Response) error {
	body, err := runtime.Payload(resp)
	if err != nil {
		return runtime.NewResponseError(err, resp)
	}
		errType := ServiceBusManagementError{raw: string(body)}
	if err := runtime.UnmarshalAsXML(resp, &errType); err != nil {
		return runtime.NewResponseError(fmt.Errorf("%s\n%s", string(body), err), resp)
	}
	return runtime.NewResponseError(&errType, resp)
}

// Get - Get the details about the Queue or Topic with the given entityName.
// If the operation fails it returns the *ServiceBusManagementError error type.
func (client *entityClient) Get(ctx context.Context, entityName string, options *EntityGetOptions) (EntityGetResponse, error) {
	req, err := client.getCreateRequest(ctx, entityName, options)
	if err != nil {
		return EntityGetResponse{}, err
	}
	resp, err := 	client.con.Pipeline().Do(req)
	if err != nil {
		return EntityGetResponse{}, err
	}
	if !runtime.HasStatusCode(resp, http.StatusOK) {
		return EntityGetResponse{}, client.getHandleError(resp)
	}
	return client.getHandleResponse(resp)
}

// getCreateRequest creates the Get request.
func (client *entityClient) getCreateRequest(ctx context.Context, entityName string, options *EntityGetOptions) (*policy.Request, error) {
	urlPath := "/{entityName}"
	if entityName == "" {
		return nil, errors.New("parameter entityName cannot be empty")
	}
	urlPath = strings.ReplaceAll(urlPath, "{entityName}", url.PathEscape(entityName))
	req, err := runtime.NewRequest(ctx, http.MethodGet, runtime.JoinPaths(client.con.Endpoint(), urlPath))
	if err != nil {
		return nil, err
	}
	reqQP := req.Raw().URL.Query()
	if options != nil && options.Enrich != nil {
		reqQP.Set("enrich", strconv.FormatBool(*options.Enrich))
	}
	if client.apiVersion != nil {
		reqQP.Set("api-version", "2017_04")
	}
	req.Raw().URL.RawQuery = reqQP.Encode()
	req.Raw().Header.Set("Accept", "application/xml, application/atom+xml")
	return req, nil
}

// getHandleResponse handles the Get response.
func (client *entityClient) getHandleResponse(resp *http.Response) (EntityGetResponse, error) {
	result := EntityGetResponse{RawResponse: resp}
	if err := runtime.UnmarshalAsXML(resp, &result.Object); err != nil {
		return EntityGetResponse{}, err
	}
	return result, nil
}

// getHandleError handles the Get error response.
func (client *entityClient) getHandleError(resp *http.Response) error {
	body, err := runtime.Payload(resp)
	if err != nil {
		return runtime.NewResponseError(err, resp)
	}
		errType := ServiceBusManagementError{raw: string(body)}
	if err := runtime.UnmarshalAsXML(resp, &errType); err != nil {
		return runtime.NewResponseError(fmt.Errorf("%s\n%s", string(body), err), resp)
	}
	return runtime.NewResponseError(&errType, resp)
}

// Put - Create or update a queue or topic at the provided entityName
// If the operation fails it returns the *ServiceBusManagementError error type.
func (client *entityClient) Put(ctx context.Context, entityName string, requestBody map[string]interface{}, options *EntityPutOptions) (EntityPutResponse, error) {
	req, err := client.putCreateRequest(ctx, entityName, requestBody, options)
	if err != nil {
		return EntityPutResponse{}, err
	}
	resp, err := 	client.con.Pipeline().Do(req)
	if err != nil {
		return EntityPutResponse{}, err
	}
	if !runtime.HasStatusCode(resp, http.StatusOK, http.StatusCreated) {
		return EntityPutResponse{}, client.putHandleError(resp)
	}
	return client.putHandleResponse(resp)
}

// putCreateRequest creates the Put request.
func (client *entityClient) putCreateRequest(ctx context.Context, entityName string, requestBody map[string]interface{}, options *EntityPutOptions) (*policy.Request, error) {
	urlPath := "/{entityName}"
	if entityName == "" {
		return nil, errors.New("parameter entityName cannot be empty")
	}
	urlPath = strings.ReplaceAll(urlPath, "{entityName}", url.PathEscape(entityName))
	req, err := runtime.NewRequest(ctx, http.MethodPut, runtime.JoinPaths(client.con.Endpoint(), urlPath))
	if err != nil {
		return nil, err
	}
	reqQP := req.Raw().URL.Query()
	if client.apiVersion != nil {
		reqQP.Set("api-version", "2017_04")
	}
	req.Raw().URL.RawQuery = reqQP.Encode()
	if options != nil && options.IfMatch != nil {
		req.Raw().Header.Set("If-Match", *options.IfMatch)
	}
	req.Raw().Header.Set("Accept", "application/xml, application/atom+xml")
	return req, runtime.MarshalAsXML(req, requestBody)
}

// putHandleResponse handles the Put response.
func (client *entityClient) putHandleResponse(resp *http.Response) (EntityPutResponse, error) {
	result := EntityPutResponse{RawResponse: resp}
	if err := runtime.UnmarshalAsXML(resp, &result.Object); err != nil {
		return EntityPutResponse{}, err
	}
	return result, nil
}

// putHandleError handles the Put error response.
func (client *entityClient) putHandleError(resp *http.Response) error {
	body, err := runtime.Payload(resp)
	if err != nil {
		return runtime.NewResponseError(err, resp)
	}
		errType := ServiceBusManagementError{raw: string(body)}
	if err := runtime.UnmarshalAsXML(resp, &errType); err != nil {
		return runtime.NewResponseError(fmt.Errorf("%s\n%s", string(body), err), resp)
	}
	return runtime.NewResponseError(&errType, resp)
}

