//go:build go1.16
// +build go1.16

// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package main

import "net/http"

// EntityDeleteResponse contains the response from method Entity.Delete.
type EntityDeleteResponse struct {
	EntityDeleteResult
	// RawResponse contains the underlying HTTP response.
	RawResponse *http.Response
}

// EntityDeleteResult contains the result from method Entity.Delete.
type EntityDeleteResult struct {
	// Any object
	Object map[string]interface{} `xml:"Object"`
}

// EntityGetResponse contains the response from method Entity.Get.
type EntityGetResponse struct {
	EntityGetResult
	// RawResponse contains the underlying HTTP response.
	RawResponse *http.Response
}

// EntityGetResult contains the result from method Entity.Get.
type EntityGetResult struct {
	// Any object
	Object map[string]interface{} `xml:"Object"`
}

// EntityPutResponse contains the response from method Entity.Put.
type EntityPutResponse struct {
	EntityPutResult
	// RawResponse contains the underlying HTTP response.
	RawResponse *http.Response
}

// EntityPutResult contains the result from method Entity.Put.
type EntityPutResult struct {
	// Any object
	Object map[string]interface{} `xml:"Object"`
}

// NamespaceGetResponse contains the response from method Namespace.Get.
type NamespaceGetResponse struct {
	NamespaceGetResult
	// RawResponse contains the underlying HTTP response.
	RawResponse *http.Response
}

// NamespaceGetResult contains the result from method Namespace.Get.
type NamespaceGetResult struct {
	NamespacePropertiesEntry
}

// RuleDeleteResponse contains the response from method Rule.Delete.
type RuleDeleteResponse struct {
	RuleDeleteResult
	// RawResponse contains the underlying HTTP response.
	RawResponse *http.Response
}

// RuleDeleteResult contains the result from method Rule.Delete.
type RuleDeleteResult struct {
	// Any object
	Object map[string]interface{} `xml:"Object"`
}

// RuleGetResponse contains the response from method Rule.Get.
type RuleGetResponse struct {
	RuleGetResult
	// RawResponse contains the underlying HTTP response.
	RawResponse *http.Response
}

// RuleGetResult contains the result from method Rule.Get.
type RuleGetResult struct {
	// Any object
	Object map[string]interface{} `xml:"Object"`
}

// RulePutResponse contains the response from method Rule.Put.
type RulePutResponse struct {
	RulePutResult
	// RawResponse contains the underlying HTTP response.
	RawResponse *http.Response
}

// RulePutResult contains the result from method Rule.Put.
type RulePutResult struct {
	// Any object
	Object map[string]interface{} `xml:"Object"`
}

// ServiceBusManagementClientListEntitiesResponse contains the response from method ServiceBusManagementClient.ListEntities.
type ServiceBusManagementClientListEntitiesResponse struct {
	ServiceBusManagementClientListEntitiesResult
	// RawResponse contains the underlying HTTP response.
	RawResponse *http.Response
}

// ServiceBusManagementClientListEntitiesResult contains the result from method ServiceBusManagementClient.ListEntities.
type ServiceBusManagementClientListEntitiesResult struct {
	// Any object
	Object map[string]interface{} `xml:"Object"`
}

// ServiceBusManagementClientListRulesResponse contains the response from method ServiceBusManagementClient.ListRules.
type ServiceBusManagementClientListRulesResponse struct {
	ServiceBusManagementClientListRulesResult
	// RawResponse contains the underlying HTTP response.
	RawResponse *http.Response
}

// ServiceBusManagementClientListRulesResult contains the result from method ServiceBusManagementClient.ListRules.
type ServiceBusManagementClientListRulesResult struct {
	// Any object
	Object map[string]interface{} `xml:"Object"`
}

// ServiceBusManagementClientListSubscriptionsResponse contains the response from method ServiceBusManagementClient.ListSubscriptions.
type ServiceBusManagementClientListSubscriptionsResponse struct {
	ServiceBusManagementClientListSubscriptionsResult
	// RawResponse contains the underlying HTTP response.
	RawResponse *http.Response
}

// ServiceBusManagementClientListSubscriptionsResult contains the result from method ServiceBusManagementClient.ListSubscriptions.
type ServiceBusManagementClientListSubscriptionsResult struct {
	// Any object
	Object map[string]interface{} `xml:"Object"`
}

// SubscriptionDeleteResponse contains the response from method Subscription.Delete.
type SubscriptionDeleteResponse struct {
	SubscriptionDeleteResult
	// RawResponse contains the underlying HTTP response.
	RawResponse *http.Response
}

// SubscriptionDeleteResult contains the result from method Subscription.Delete.
type SubscriptionDeleteResult struct {
	// Any object
	Object map[string]interface{} `xml:"Object"`
}

// SubscriptionGetResponse contains the response from method Subscription.Get.
type SubscriptionGetResponse struct {
	SubscriptionGetResult
	// RawResponse contains the underlying HTTP response.
	RawResponse *http.Response
}

// SubscriptionGetResult contains the result from method Subscription.Get.
type SubscriptionGetResult struct {
	// Any object
	Object map[string]interface{} `xml:"Object"`
}

// SubscriptionPutResponse contains the response from method Subscription.Put.
type SubscriptionPutResponse struct {
	SubscriptionPutResult
	// RawResponse contains the underlying HTTP response.
	RawResponse *http.Response
}

// SubscriptionPutResult contains the result from method Subscription.Put.
type SubscriptionPutResult struct {
	// Any object
	Object map[string]interface{} `xml:"Object"`
}

